FROM node:13.1-alpine as build

COPY * /usr/src/app/
ENTRYPOINT ["/usr/src/app"]
RUN npm cache verify && npm doctor
RUN npm install && npm run build

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
